### ISSUE TITLE
Installation from github seems to fail if pandas not already installed

### ISSUE THREAD

**Issue by tomwallis** [circstat/pycircstat#46]
I was just trying to install pycircstat in an environment that did not contain `pandas`. The installation (via `pip install git+https://github.com/circstat/pycircstat.git`) seemed to hang indefinitely. Once I installed pandas the pycircstat install proceeded with no problems.

It seems as if the pycircstat dependencies are not being handled correctly by pip? Perhaps because they're listed as "setup_requires"? It would be good to have some warning then.

**Comment by avdaranyi** [comment]
This would fix it: #69
