### ISSUE TITLE
Request: Listing on PyPI

### ISSUE THREAD

**Issue by OrganicIrradiation** [circstat/pycircstat#47]
I wanted to request that the package be listed on PyPI so that it can be (easily) installed via pip. Right now, it is possible to install via the github repository with ```pip install git+git://github.com/circstat/pycircstat.git```.  However, it would be great to have it in the Python Package Index so that we could install/upgrade with ```pip install pycircstat```.

**Comment by fabiansinz** [comment]
Good idea. We will put it up as soon as we can devote some time to it. Should happen this week.

**Comment by fabiansinz** [comment]
`pycircstat` should be available via pip now.

**Comment by philippberens** [comment]
Danke, Fabi!
