### ISSUE TITLE
Median correctness

### ISSUE THREAD

**Issue by aplavin** [circstat/pycircstat#52]
Are you sure that the `median` function in `descriptive.py` is correct? As I know, median is defined to be a value which minimizes sum of distances to all samples (just like arithmetical mean minimizes squares of distances), but reading the code I see that your function finds a value lying on the diameter which has half of the points on each side.

Generally, these values may of course be different. Here is my basic implementation (for 1d only), which simply follows the definition:

``` python
def median(angs):
    pdists = pairwise_cdiff(angs, angs)
    pdists = np.abs(pdists).sum(1)
    return angs[np.argmin(pdists)]
```

**Comment by fabiansinz** [comment]
Hey @aplavin ,

the median is also the 50%-percentile. You get that if you compute the point of minimal absolute deviation for a general distribution. So basically you just wrote a different estimator of the median. Neither of them are incorrect, but they may have different statistical properties. If you want, you can include you estimator in the median function and submit a pull request.
