### ISSUE TITLE
error when providing ci in mean calculation

### ISSUE THREAD

**Issue by Khalilsqu** [circstat/pycircstat#60]
```
import pycircstat
a = 180 + np.random.randint(-50, 50, size=60)
a = np.deg2rad(a)

np.rad2deg(pycircstat.mean(a, ci=0.95))

ValueError: setting an array element with a sequence.
```
But it works fine without ci

```
np.rad2deg(pycircstat.mean(a))
178.57652847866993
```

python 3.6 anaconda 
OS: windows 10 64 bit
pycirctats: from pypi

**Comment by fabiansinz** [comment]
If you specify `ci=` you get multiple output arguments. `np.rad2deg` can't deal with that.

**Comment by Khalilsqu** [comment]
Okay, Thanks, appreciate it, and thank you very much for this amazing library. helped me a lot in my PhD

**Comment by fabiansinz** [comment]
No problem. Glad it's useful to you.
