### ISSUE TITLE
Removal of scipy.misc aliases (e.g. comb) causes errors.

### ISSUE THREAD

**Issue by adamltyson** [circstat/pycircstat#65]
Scipy 1.3.0 has removed the deprecated aliases to a number of functions (e.g. `scipy.misc.comb`) which causes problems in e.g. https://github.com/circstat/pycircstat/blob/648ff7c8f0db08bb567097918269aba37cd7a802/pycircstat/tests.py#L121-L123

This can be fixed by using e.g. `scipy.special.comb` or specifying `scipy<=1.2.1` as a dependency.

**Comment by adamltyson** [comment]
Fixed in https://github.com/circstat/pycircstat/pull/66

**Comment by ctw** [comment]
I also just submitted #70 that fixes this issue (hadn't seen that this was already in a pull requests).

**Comment by philippberens** [comment]
thanks - did that
